apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-sample-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-sample-app
  template:
    metadata:
      labels:
        app: workshop-sample-app
    spec:
      containers:
        - name: workshop-sample-app
          image: mcr.microsoft.com/azurelinux/base/nginx:1.28
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10